# Generated by Django 3.1.3 on 2020-11-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date_update',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_update',
            new_name='date_updated',
        ),
    ]
